name: Test and Deploy Laravel to Prod Server

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 8.2
        extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

    - name: Install dependencies
      run: composer install --prefer-dist --no-progress --no-suggest --no-interaction --optimize-autoloader

    - name: Copy .env
      run: cp .env.example .env

    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite

    - name: Generate application key and clear cache
      run: |
        php artisan key:generate
        php artisan config:cache

    - name: Run tests
      run: |
        php artisan test

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:

    - name: Executing Remote SSH Commands
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.PRODUCTION_SERVER }}
        username: ${{ secrets.PRODUCTION_USER }}
        key: ${{ secrets.PRODUCTION_KEY }}
        port: ${{ secrets.PRODUCTION_PORT }}
        script: |
          cd ${{ secrets.PRODUCTION_PATH }}
          php artisan down
          git pull origin master
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
          php artisan view:cache
          php artisan up